export const currencies: [code: string, symbol: string][] = [
  ['AUD', '$'],
  ['BRL', 'R$'],
  ['CAD', '$'],
  ['CNY', '\u00a5'],
  ['EUR', '\u20ac'],
  ['GBP', '\u00a3'],
  ['HKD', '$'],
  ['INR', '\u20b9'],
  ['JPY', '\u00a5'],
  ['KRW', '\u20a9'],
  ['MXN', '$'],
  ['NOK', 'kr'],
  ['NZD', '$'],
  ['PLN', 'z\u0142'],
  ['RUB', '\u20bd'],
  ['SEK', 'kr'],
  ['SGD', '$'],
  ['USD', '$'],
  ['ZAR', 'R'],
];
